// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbpMtu1QYlqXX5mIjYtr9L8iwyFqw2KRQ',
    appId: '1:764756571922:web:fba6f61bb1f9904c36e5cb',
    messagingSenderId: '764756571922',
    projectId: 'fir-24689',
    authDomain: 'fir-24689.firebaseapp.com',
    storageBucket: 'fir-24689.firebasestorage.app',
    measurementId: 'G-3MDV0099M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiT_Ra2MpvT6ff4Fp2wJ0SkKi5R_OEkUQ',
    appId: '1:764756571922:android:614203deee0e557936e5cb',
    messagingSenderId: '764756571922',
    projectId: 'fir-24689',
    storageBucket: 'fir-24689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvvI-272GLd3RwP09Bs9fx7svY6wYxkr0',
    appId: '1:764756571922:ios:1b5023d8eb4329c036e5cb',
    messagingSenderId: '764756571922',
    projectId: 'fir-24689',
    storageBucket: 'fir-24689.firebasestorage.app',
    iosBundleId: 'com.Trending.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvvI-272GLd3RwP09Bs9fx7svY6wYxkr0',
    appId: '1:764756571922:ios:1b5023d8eb4329c036e5cb',
    messagingSenderId: '764756571922',
    projectId: 'fir-24689',
    storageBucket: 'fir-24689.firebasestorage.app',
    iosBundleId: 'com.Trending.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbpMtu1QYlqXX5mIjYtr9L8iwyFqw2KRQ',
    appId: '1:764756571922:web:96bb25e3137fbfe536e5cb',
    messagingSenderId: '764756571922',
    projectId: 'fir-24689',
    authDomain: 'fir-24689.firebaseapp.com',
    storageBucket: 'fir-24689.firebasestorage.app',
    measurementId: 'G-69VP46HNN6',
  );
}
